export const SCREEN_PATHS = {
  login: '/',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  home: '/home',
  patient: '/patients/:id',
  patients: '/patients',
  professional: '/professionals/:id',
  professionals: '/professionals',
  appointment: '/appointments/:id',
  appointments: '/appointments',
  registerPatient: '/patients/register',
  registerProfessional: '/professional/register',
  registerAppointment: '/appointments/register',
  calendar: '/calendar',
  financialReport: '/financial-report',
};
